### ISSUE TITLE
Typo dans description de conf

### ISSUE THREAD

**Issue by vpoulailleau** [AFPy/pyconfr-2023#18]
J'imagine que les données ne sont pas dans ce repo, du coup pas de PR, désolé ! C'est dans ponyconf ?

Dans le texte de https://www.pycon.fr/2023/fr/talks/30m.html#monorepo-python-avec-environne

« une startup du domaine médicale » a un « e » en trop à la fin de « médical ».

Au passage, j'espère que c'est le bon endroit où poster ce genre de remarque… Sinon, re-désolé :wink:

**Comment by grewn0uille** [comment]
Bonjour,

C’est effectivement dans ponyconf.

C’est corrigé ! Merci pour le report (c’est le bon endroit :))
