### ISSUE TITLE
Infos manquantes concernant les sprints

### ISSUE THREAD

**Issue by sblondon** [AFPy/pyconfr-2023#21]
Bonjour,

le site affiche le programme pour les conférences mais il manque des informations concernant les [sprints](https://www.pycon.fr/2023/fr/talks/sprint.html). D'après cette page, les sprints commencent à 10h. On ne connait pas l'endroit où se retrouver (la salle ou l'amphi) et il y a peut-être une réunion de présentation/explication de comment ça se déroule avant les sprints proprement dit. Un paragraphe avec ces informations en haut de page me semble nécessaire.

Je peux faire une PR si j'ai les infos et que vous pensez que ça vous fait gagner du temps.

**Comment by grewn0uille** [comment]
Bonjour,

Les sprints s’organisent généralement le jeudi matin, selon les personnes présentes et les salles disponibles. Nous ne savons pas à l’avance où se déroule exactement chaque sprint, il est difficile d’indiquer plus d’informations à l’avance sur le site.

Pas d’inquiétude : en plus de l’affichage qui sera réalisé avant 10 heures, les personnes à l’accueil sauront aiguiller les personnes qui voudront participer !

**Comment by sblondon** [comment]
S'il y avait eu cette phrase (ou toute autre formulation du même genre) entre le titre et la liste des sprints, je n'aurai pas posé la question:

> La liste et les horaires des sprints sont définies. Pour les derniers détails d'organisation, consultez les personnes à l'accueil ou l'affichage proche.


Est-ce que ça semble pertinent de l'ajouter sur la page?

**Comment by grewn0uille** [comment]
La phrase a été rajoutée :)
