### ISSUE TITLE
Lien vers AFPy.org, le Discourse, ... ?

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/pyconfr-2023#23]
Est-ce que le site de la PyConFr manque de liens vers l'AFPy ? Éventuellement vers le Discourse ?

**Comment by grewn0uille** [comment]
On peut rajouter un lien vers le Discourse dans le footer et dans la news. Genre "Venez discuter avec nous sur notre groupe Telegram ou sur notre Discourse" ?

Après l’AFPy y a des liens sur la page d’accueil et le footer. On peut peut-être mettre un lien vers le site dès qu’il y a AFPy d’écrit ? (et qu’il y a pas déjà un lien vers la charte)

**Comment by grewn0uille** [comment]
Je viens de rajouter le lien du Discourse dans le footer et la news.

Pour le lien vers l’AFPy, le mot apparait dans le code de conduite (où y a déjà un lien vers la charte sur le site de l’AFPy) et sur les pages pour les bourses qui sont fermées, du coup j’y ai pas touché.

Je sais pas si c’est suffisant ou pas.

**Comment by JulienPalard** [comment]
Ça m'va !

**Comment by JulienPalard** [comment]
Merci @grewn0uille !
