### ISSUE TITLE
Séparation des jours dans le programme

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/pyconfr-2023#26]
La séparation « Dimanche 19 février » entre le planning du samedi et le planning du dimanche est peut-être trop discrète : je viens d'avoir un sponsor au téléphone qui pensait que le samedi se terminait avec la « Clôture du dimanche » à 15h30.

**Comment by grewn0uille** [comment]
La date du jour (samedi / dimanche) reste maintenant fixée quand on scrolle, comme pour les amphis. Ça devrait être plus clair comme ça !
